name: Synchronize to forked repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0
          ref: main

      - name: Add remote-url
        run: |
          git remote add forked-repo https://jun1378527:${{ secrets.AUTO_ACTIONS }}@github.com/jun1378527/moa-moa.git
          git config user.name "jun1378527"
          git config user.email "${{ secrets.EMAIL }}"

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo main

      - name: Clean up
        run: |
          git remote remove forked-repo
