name: Synchronize and Deploy to Vercel

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sync-and-deploy:
    name: Sync forked repo and Deploy Preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel environment variables
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        id: deploy
        run: |
          PREVIEW_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | tail -n 1)
          echo "preview-url=$PREVIEW_URL" >> $GITHUB_ENV

      - name: Verify PREVIEW_URL
        run: echo "Preview URL: ${{ env.preview-url }}"

      - name: Comment Vercel Preview URL on PR
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          PREVIEW_URL=${{ env.preview-url }}
          echo "Posting URL: $PREVIEW_URL"
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -d "{\"body\":\"🚀 Vercel Preview URL: ${PREVIEW_URL}\"}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
